### ISSUE TITLE
Set up automatic deployment of master branch

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-run#13]
We should remove the need for manual deployments of the documentation. Instead we should automatically deploy the master branch if new changes are pushed.

**Comment by geigerzaehler** [comment]
We might want to investigate Github actions for this. I suspect it would be much simpler than integrating with Buildkite. Especially because of security concerns about Github permissions.

**Comment by NunoAlexandre** [comment]
True. When I gave this a quick look Travis was still the suggestion solution but I would be glad to give actions a try.

**Comment by geigerzaehler** [comment]
> True. When I gave this a quick look Travis was still the suggestion solution but I would be glad to give actions a try.

Travis has no advantage over Buildkite. It would just fracture our CI setup. Buildkite would be preferable but it might be too complex to set up. I’d also like @kim to chime in on this.

**Comment by NunoAlexandre** [comment]
Sorry, I wasn't clear. I'm not suggesting using Travis, I had suggested using Buildkite. Just saying that when I looked into automating our docossaurus, Travis is still the suggested, probably running Ubuntu 2008 :sob:

**Comment by geigerzaehler** [comment]
Maybe it’s not a good idea to update this merges to the master branch after all. We should consider the relation to releases of the binaries. Maybe it makes sense to have a release and a master/staging deployment.

**Comment by geigerzaehler** [comment]
I think it’s still a good idea to deploy master automatically on merge despite my previous comment. Until we have a better versioning/release scheme for both this site and our binaries we should move forward with this. We won’t forget to deploy the site on merges and we will have the necessary infrastructure in place to extend.

I propose we create a buildkite pipeline for this project and run [`docosaurus publish`](https://docusaurus.io/docs/en/commands#docusaurus-publish). For write access to the repo we’ll provide a SSH deploy key via buildkite secrets.

**Comment by NunoAlexandre** [comment]
Sounds good to me. To avoid publishing all things merged to master, we can publish only when a tag is present, where the tag would be associated with the registry binaries release (i.e, the date). It should be simple to implement and at least it gives us a 1:1 relationship between the docs and the binaries.
