### ISSUE TITLE
Retire the website and archive this repo

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-run#48]
Since the registry is actively developed anymore I suggest we retire the `registry.radicle.xyz` website by redirecting it to `radicle.xyz` and archive this repo.

cc @NunoAlexandre, @CodeSandwich, @lftherios

**Comment by teohhanhui** [comment]
Is this related to this section on [radicle.xyz](https://radicle.xyz)?

> Ethereum
> (opt-in)
> 
> Harness the power of decentralized organizations and digital money. Fund and sustain your open-source work without relying on intermediaries.

**Comment by NunoAlexandre** [comment]
> Is this related to this section on [radicle.xyz](https://radicle.xyz)?
> 
> > Ethereum
> > (opt-in)
> > Harness the power of decentralized organizations and digital money. Fund and sustain your open-source work without relying on intermediaries.

@teohhanhui kinda, yes. This project was our custom-made attempt. In the meantime, we have dropped it in favour of using Ethereum (smart contracts). In case you want to dig further, have a look at the [Radicle Contracts](https://github.com/radicle-dev/radicle-contracts).

**Comment by teohhanhui** [comment]
Is there anything user-facing that we can use yet? Or is that coming soon?

**Comment by geigerzaehler** [comment]
@teohhanhui: You can find an experimental implementation in [Radicle Upstream](https://github.com/radicle-dev/radicle-upstream/blob/master/FUNDING.md). At the moment the feature works only against a local environment but we are starting to test this on the testnet and want to release it soon.
